types:
  - &m5base
      type: select
      target: define
      label: 'M5 Atom light Base'
      key: m5lightbase
      values:
        - label: "CAN KIT"
          value: M5_CAN_KIT
          description: "M5 Stack CAN Kit"
          url: "https://docs.m5stack.com/en/atom/atom_can"
          resource: can
        - value: M5_SERIAL_KIT_232
          description: "M5 Stack RS232 Base"
          label: "Atomic RS232 Base"
          url: "https://docs.m5stack.com/en/atom/Atomic%20RS232%20Base"
          resource: serial
        - value: M5_SERIAL_KIT_485
          description: "M5 Stack RS485 Base"
          label: "Atomic RS485 Base"
          url: "https://docs.m5stack.com/en/atom/Atomic%20RS485%20Base"
          resource: serial
        - value: M5_GPS_KIT
          description: "M5 Stack Gps Kit"
          label: "Gps Base"
          url: "https://docs.m5stack.com/en/atom/atomicgps"
          resource: serial

  - &m5groovei2c
    type: multi
    key: m5groovei2c
    label: "M5 I2C Groove Units"
    values:
  - &m5groovecan
    type: select
    key: m5groovecan
    target: define
    label: "M5 Groove CAN Units"
    values:
      - label: "CAN Unit"
        url: "https://docs.m5stack.com/en/unit/can"
        description: "M5 Can unit"
        value: M5_CANUNIT
        resource: can    
  - &m5grooveserial
    type: select
    label: "M5 Groove Serial Unit"
    target: define
    key: m5grooveserial
    values:
      - label: "RS485"
        key: unit485
        value: SERIAL_GROOVE_485
        description: "M5 RS485 unit"
        url: "https://docs.m5stack.com/en/unit/rs485"
        resource: serial
      - label: "Tail485"
        value: SERIAL_GROOVE_485
        key: tail485
        description: "M5 Tail 485"
        url: "https://docs.m5stack.com/en/atom/tail485"
        resource: serial
      - label: "Gps Unit"
        value: M5_GPS_UNIT
        description: "M5 Gps Unit"
        url: "https://docs.m5stack.com/en/unit/gps"
        resource: serial

  - &m5groove
    type: select
    key: m5groove
    label: 'M5 groove type'
    values:
      - label: 'CAN'
        children:
        - *m5groovecan 
      - label: 'I2C'
        children:
        - *m5groovei2c
      - label: 'Serial'
        children:
        - *m5grooveserial
resources:
  default: &esp32default
    serial: 2
    can: 1
    i2c: 1 

config:
  children:
    - type: select
      target: environment
      label: 'Board'
      key: board
      values: 
        - value: m5stack-atom-generic
          label: m5stack-atom
          description: "M5 Stack Atom light"
          url: "http://docs.m5stack.com/en/core/atom_lite"
          resource: *esp32default
          children:
            - *m5base
            - *m5groove
        - value: m5stack-atoms3-generic
          label: m5stack-atoms3
          description: "M5 Stack AtomS3 light"
          url: "http://docs.m5stack.com/en/core/AtomS3%20Lite"
          resource: *esp32default
          children:
            - *m5base    
            - *m5groove